version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    network_mode: bridge
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
